spring.application.name=organics

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/shreekrishna_organics
spring.datasource.username=root
spring.datasource.password=redhat


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=900000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}